#!/bin/bash
# Auto-generated surgical fix plan based on RCA analysis and debugging evidence
# Generated by fix-plan.rs

echo "=== SURGICAL FIX EXECUTION PLAN ==="
echo "Based on RCA analysis and debugging forensics"
echo

echo "# FIX 1: Missing nuke-all.sh nuclear cleanup wrapper"
cat > /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/nuke-all.sh << 'EOF'
#!/bin/bash
# Nuclear cleanup wrapper for ollama - removes ALL models and data
# WARNING: This script will destroy all ollama data

set -euo pipefail

echo "WARNING: This will delete ALL ollama models and data"
echo "Current ollama data size: $(du -sh /FuZe/ollama 2>/dev/null || echo 'N/A')"
echo "Press Ctrl+C to abort, or wait 10 seconds to continue..."
sleep 10

# Stop all ollama services
systemctl stop ollama.service ollama-test-a.service ollama-test-b.service 2>/dev/null || true

# Kill any remaining ollama processes
pkill -f ollama || true
sleep 2

# Remove all model data
rm -rf /FuZe/ollama/manifests/*
rm -rf /FuZe/ollama/blobs/*
rm -rf /FuZe/baked/ollama/*

echo "Nuclear cleanup completed - all ollama data removed"
EOF
chmod +x /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/nuke-all.sh
echo "Fixed: Missing nuke-all.sh nuclear cleanup wrapper"

echo "# FIX 2: service-cleanup.sh missing MODELDIR path configuration"
# Fix MODELDIR path in /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/service-cleanup.sh
sed -i 's|MODELDIR=.*|MODELDIR="/FuZe/ollama"|g' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/service-cleanup.sh
sed -i 's|/FuZe/models/ollama|/FuZe/ollama|g' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/service-cleanup.sh
echo "Fixed: service-cleanup.sh missing MODELDIR path configuration"

echo "# FIX 3: store-cleanup.sh missing CANON/ALT_DEFAULT paths"
# Fix CANON/ALT_DEFAULT paths in /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/store-cleanup.sh
sed -i 's|CANON_DEFAULT=.*|CANON_DEFAULT="/FuZe/ollama"|g' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/store-cleanup.sh
sed -i 's|ALT_DEFAULT=.*|ALT_DEFAULT="/FuZe/baked/ollama"|g' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/store-cleanup.sh
sed -i 's|/FuZe/models/ollama|/FuZe/ollama|g' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/store-cleanup.sh
echo "Fixed: store-cleanup.sh missing CANON/ALT_DEFAULT paths"

echo "# FIX 4: cleanup-variants.sh missing MATCH_RE regex pattern for malformed names"
# Fix regex patterns in /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh to handle malformed model names
cat >> /tmp/cleanup-variants-fix.patch << 'EOF'
# Enhanced regex patterns to handle malformed model names
# Original pattern: MATCH_RE="^LLM-FuZe-.*-(gpu[0-9]+|[0-9]+ti|[0-9]+)-ng[0-9]+:latest$"
# Enhanced pattern to catch malformed names:
MATCH_RE="^LLM-FuZe-.*"
MALFORMED_RE="^LLM-FuZe-LLM-FuZe-.*"
GPU_PATTERN_RE="(gpu[0-9]+|[0-9]+ti|[0-9]+|3090ti|5090)"
EOF
# Apply enhanced regex to /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MATCH_RE=/c\MATCH_RE="^LLM-FuZe-.*"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MATCH_RE=/a\MALFORMED_RE="^LLM-FuZe-LLM-FuZe-.*"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MALFORMED_RE=/a\GPU_PATTERN_RE="(gpu[0-9]+|[0-9]+ti|[0-9]+|3090ti|5090)"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
echo "Fixed: cleanup-variants.sh missing MATCH_RE regex pattern for malformed names"

echo "# FIX 5: Mixed GPU naming patterns (gpu0 vs 3090ti vs 5090) breaking cleanup logic"
# Fix regex patterns in /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh to handle malformed model names
cat >> /tmp/cleanup-variants-fix.patch << 'EOF'
# Enhanced regex patterns to handle malformed model names
# Original pattern: MATCH_RE="^LLM-FuZe-.*-(gpu[0-9]+|[0-9]+ti|[0-9]+)-ng[0-9]+:latest$"
# Enhanced pattern to catch malformed names:
MATCH_RE="^LLM-FuZe-.*"
MALFORMED_RE="^LLM-FuZe-LLM-FuZe-.*"
GPU_PATTERN_RE="(gpu[0-9]+|[0-9]+ti|[0-9]+|3090ti|5090)"
EOF
# Apply enhanced regex to /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MATCH_RE=/c\MATCH_RE="^LLM-FuZe-.*"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MATCH_RE=/a\MALFORMED_RE="^LLM-FuZe-LLM-FuZe-.*"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
sed -i '/MALFORMED_RE=/a\GPU_PATTERN_RE="(gpu[0-9]+|[0-9]+ti|[0-9]+|3090ti|5090)"' /home/fuze/GitHub/FuZeCORE.ai/factory/LLM/refinery/stack/ollama/cleanup-variants.sh
echo "Fixed: Mixed GPU naming patterns (gpu0 vs 3090ti vs 5090) breaking cleanup logic"

echo "=== END OF SURGICAL FIX PLAN ==="
echo "# This plan was generated but NOT executed"
echo "# Review each section before manual execution"
